# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# === OHH-MY-ZSH Stuff === #


export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bira"

plugins=(git)

source $ZSH/oh-my-zsh.sh


# === Aliases === #


alias vim="nvim"


# === Variables === #

# Display dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Set defaultneditor to nvim
export EDITOR='nvim'

# Add gopath to path
export PATH="$PATH:$(go env GOPATH)/bin" 

